### ISSUE TITLE
Implement CI/CD in GitHub

### ISSUE THREAD

**Issue by WilWa** [WalterDevelopment/screeps#8]
- [x] Implement CI/CD

**Comment by WilWa** [comment]
We need to figure out why it isn't actually publishing to the screeps servers in the public.js. We're really close. For some reason it looks like it is not reading our environment variables, possibly because they're not getting set, or something is wrong with the yaml. We're working on adding a little bit of logging, but ran into issues with the merging of that.

**Comment by WilWa** [comment]
I think I got this fixed. Need to confirm with Daniel.

**Comment by xsolvia** [comment]
good
